/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
/**
 *
 * @author win7
 */
public class GameJFrame extends javax.swing.JFrame
{

    /**
     * Creates new form GameJFrame
     */
     StringBuilder word = new StringBuilder();
     StringBuilder buff = new StringBuilder();
     StringBuilder charNotinWord = new StringBuilder();
     boolean replacedCharacter=false;
     int NumberofTries = 9;
     int imageCount=1;
    public GameJFrame()
    {
        initComponents();
        System.out.println("GameJFrame called");
        //lbl_image.setSize(250, 290);
        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/h1.png"))); 
        
        
        //Init all components
        // select word from db
        java.awt.Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK, true);
        String tries =String.valueOf(NumberofTries);
        lbl_Tries.setText(tries);
        word.append("CHARACTER");
        
        int length = word.length();
        //Set buffer
        for (int x=0; x < length; x++)
        {
            buff.append("_");
        }
        
        int boxesToRemove = 11 - length; 
        
           if(boxesToRemove !=0)
           {
               c_10.setVisible(false);
               boxesToRemove --;
           }
           if(boxesToRemove !=0)
           {
               c_9.setVisible(false);
               boxesToRemove --;
           }
           if(boxesToRemove !=0)
           {
               c_8.setVisible(false);
               boxesToRemove --;
           }
           if(boxesToRemove !=0)
           {
               c_7.setVisible(false);
               boxesToRemove --;
           }
           if(boxesToRemove !=0)
           {
               c_6.setVisible(false);
               boxesToRemove --;
           }
           if(boxesToRemove !=0)
           {
               c_5.setVisible(false);
               boxesToRemove --;
           }
           if(boxesToRemove !=0)
           {
               c_4.setVisible(false);
               boxesToRemove --;
           }
           if(boxesToRemove !=0)
           {
               c_5.setVisible(false);
               boxesToRemove --;
           }
           if(boxesToRemove !=0)
           {
               c_4.setVisible(false);
               boxesToRemove --;
           }
           if(boxesToRemove !=0)
           {
               c_3.setVisible(false);
               boxesToRemove --;
           }
           if(boxesToRemove !=0)
           {
               c_2.setVisible(false);
               boxesToRemove --;
           }
            if(boxesToRemove !=0)
           {
               c_1.setVisible(false);
               boxesToRemove --;
           }
           
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        c_0 = new javax.swing.JTextField();
        c_1 = new javax.swing.JTextField();
        c_2 = new javax.swing.JTextField();
        c_3 = new javax.swing.JTextField();
        c_4 = new javax.swing.JTextField();
        c_5 = new javax.swing.JTextField();
        c_6 = new javax.swing.JTextField();
        c_7 = new javax.swing.JTextField();
        c_8 = new javax.swing.JTextField();
        c_9 = new javax.swing.JTextField();
        c_10 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_character = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbl_previous = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_Tries = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setFocusable(false);
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);

        c_0.setEditable(false);
        c_0.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_0.setText("_");
        c_0.setAutoscrolls(false);
        c_0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_0.setDoubleBuffered(true);
        c_0.setFocusable(false);
        c_0.setMaximumSize(new java.awt.Dimension(10, 10));
        c_0.setMinimumSize(new java.awt.Dimension(10, 10));
        c_0.setRequestFocusEnabled(false);
        c_0.setVerifyInputWhenFocusTarget(false);

        c_1.setEditable(false);
        c_1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_1.setText("_");
        c_1.setAutoscrolls(false);
        c_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_1.setDoubleBuffered(true);
        c_1.setFocusable(false);
        c_1.setMaximumSize(new java.awt.Dimension(10, 10));
        c_1.setMinimumSize(new java.awt.Dimension(10, 10));
        c_1.setRequestFocusEnabled(false);
        c_1.setVerifyInputWhenFocusTarget(false);

        c_2.setEditable(false);
        c_2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_2.setText("_");
        c_2.setAutoscrolls(false);
        c_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_2.setDoubleBuffered(true);
        c_2.setFocusable(false);
        c_2.setMaximumSize(new java.awt.Dimension(10, 10));
        c_2.setMinimumSize(new java.awt.Dimension(10, 10));
        c_2.setRequestFocusEnabled(false);
        c_2.setVerifyInputWhenFocusTarget(false);

        c_3.setEditable(false);
        c_3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_3.setText("_");
        c_3.setAutoscrolls(false);
        c_3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_3.setDoubleBuffered(true);
        c_3.setFocusable(false);
        c_3.setMaximumSize(new java.awt.Dimension(10, 10));
        c_3.setMinimumSize(new java.awt.Dimension(10, 10));
        c_3.setRequestFocusEnabled(false);
        c_3.setVerifyInputWhenFocusTarget(false);

        c_4.setEditable(false);
        c_4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_4.setText("_");
        c_4.setAutoscrolls(false);
        c_4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_4.setDoubleBuffered(true);
        c_4.setFocusable(false);
        c_4.setMaximumSize(new java.awt.Dimension(10, 10));
        c_4.setMinimumSize(new java.awt.Dimension(10, 10));
        c_4.setRequestFocusEnabled(false);
        c_4.setVerifyInputWhenFocusTarget(false);

        c_5.setEditable(false);
        c_5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_5.setText("_");
        c_5.setAutoscrolls(false);
        c_5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_5.setDoubleBuffered(true);
        c_5.setFocusable(false);
        c_5.setMaximumSize(new java.awt.Dimension(10, 10));
        c_5.setMinimumSize(new java.awt.Dimension(10, 10));
        c_5.setRequestFocusEnabled(false);
        c_5.setVerifyInputWhenFocusTarget(false);

        c_6.setEditable(false);
        c_6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_6.setText("_");
        c_6.setAutoscrolls(false);
        c_6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_6.setDoubleBuffered(true);
        c_6.setFocusable(false);
        c_6.setMaximumSize(new java.awt.Dimension(10, 10));
        c_6.setMinimumSize(new java.awt.Dimension(10, 10));
        c_6.setRequestFocusEnabled(false);
        c_6.setVerifyInputWhenFocusTarget(false);

        c_7.setEditable(false);
        c_7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_7.setText("_");
        c_7.setAutoscrolls(false);
        c_7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_7.setDoubleBuffered(true);
        c_7.setFocusable(false);
        c_7.setMaximumSize(new java.awt.Dimension(10, 10));
        c_7.setMinimumSize(new java.awt.Dimension(10, 10));
        c_7.setRequestFocusEnabled(false);
        c_7.setVerifyInputWhenFocusTarget(false);

        c_8.setEditable(false);
        c_8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_8.setText("_");
        c_8.setAutoscrolls(false);
        c_8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_8.setDoubleBuffered(true);
        c_8.setFocusable(false);
        c_8.setMaximumSize(new java.awt.Dimension(10, 10));
        c_8.setMinimumSize(new java.awt.Dimension(10, 10));
        c_8.setRequestFocusEnabled(false);
        c_8.setVerifyInputWhenFocusTarget(false);

        c_9.setEditable(false);
        c_9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_9.setText("_");
        c_9.setAutoscrolls(false);
        c_9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_9.setDoubleBuffered(true);
        c_9.setFocusable(false);
        c_9.setMaximumSize(new java.awt.Dimension(10, 10));
        c_9.setMinimumSize(new java.awt.Dimension(10, 10));
        c_9.setRequestFocusEnabled(false);
        c_9.setVerifyInputWhenFocusTarget(false);

        c_10.setEditable(false);
        c_10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_10.setText("_");
        c_10.setAutoscrolls(false);
        c_10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        c_10.setDoubleBuffered(true);
        c_10.setFocusable(false);
        c_10.setMaximumSize(new java.awt.Dimension(10, 10));
        c_10.setMinimumSize(new java.awt.Dimension(10, 10));
        c_10.setRequestFocusEnabled(false);
        c_10.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(c_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(c_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jLabel1.setText("Enter character");

        txt_character.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_character.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_character.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setText("previous selections");

        lbl_previous.setBackground(new java.awt.Color(255, 255, 255));
        lbl_previous.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_previous.setText(":");
        lbl_previous.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("No of tries left:");

        lbl_Tries.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Tries.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Tries.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Tries.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lbl_Tries.setPreferredSize(new java.awt.Dimension(30, 30));

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h1.png"))); // NOI18N

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_character, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jButton1)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_Tries, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_character, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_Tries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        System.out.println("submit pressed");
        
        String ch = txt_character.getText().toUpperCase();
        if(ch.matches("[A-Z]+"))
        {
         System.out.println(ch);
         if(ch.length() !=1)
            {
                JOptionPane.showMessageDialog(null, "Enter single Character!");
                txt_character.setText("");
                txt_character.requestFocus();
            }else if (ch.length() ==0)
            {
                JOptionPane.showMessageDialog(null, "Enter Character!");
             txt_character.setText("");
             txt_character.requestFocus();
            }else
            {
                //Find character in word and replace tick by character
                //NumberofTries--;
                Replace(word, ch);
                txt_character.setText("");
                txt_character.requestFocus();
            }
        }else
            {
                JOptionPane.showMessageDialog(null, "Enter a Character!");
                txt_character.setText("");
                txt_character.requestFocus();
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed
public void Replace(StringBuilder word ,String ch)
{
    //Replace character in buffer if it appears.
    for(int i=0; i< word.length(); i++)
    {
        char c = word.charAt(i);
        char charact = ch.charAt(0);
        if (charact == c)
        {
            buff.setCharAt(i, charact);
            replacedCharacter=true;  
        }
    }
    //
    if(replacedCharacter == true)
    {
        updateDisplay(buff);
    }
    
    if(word.indexOf(ch) == -1)
        {
          JOptionPane.showMessageDialog(null, "Character not in word!");
          //Make sound
          
          charNotinWord.append(ch);
          charNotinWord.append(" ");
          
          lbl_previous.setText(charNotinWord.toString());
          NumberofTries--;
          String tries =String.valueOf(NumberofTries);
          lbl_Tries.setText(tries);
          imageCount++;
          StringBuilder imageName = new StringBuilder();
          String imgNumber =String.valueOf(imageCount);
          imageName.append("h");
          imageName.append(imgNumber);
          imageName.append(".png");
          System.out.println("image: " + imageName);
          lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/"+imageName)));
          
          if (NumberofTries == 0)
          {
             JOptionPane.showMessageDialog(null, "You lose!"); 
             //Guy hangs
             // Sound
          }
        }
    
}
public void updateDisplay(StringBuilder buff)
{
    //Update characters and make sound
    int length = buff.length();
    int pos = 0;
    int numberOfCharactersToChange = length - pos;
    if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(0);
        String c0 = String.valueOf(c);
        c_0.setText(c0);
        pos++;
        numberOfCharactersToChange = length - pos;
    } 
    
    if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(1);
        String c1 = String.valueOf(c);
        c_1.setText(c1);
        pos++;
        numberOfCharactersToChange = length - pos;
    }
    
        if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(2);
        String c2 = String.valueOf(c);
     c_2.setText(c2);
     pos++;
     numberOfCharactersToChange = length - pos;
    }
    
        if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(3);
        String c3 = String.valueOf(c);
     c_3.setText(c3);
     pos++;
     numberOfCharactersToChange = length - pos;
    }
    
       if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(4);
        String c4 = String.valueOf(c);
     c_4.setText(c4);
     pos++;
     numberOfCharactersToChange = length - pos;
    } 
        
         if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(5);
        String c5 = String.valueOf(c);
     c_5.setText(c5);
     pos++;
     numberOfCharactersToChange = length - pos;
    }  
        
          if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(6);
        String c6 = String.valueOf(c);
     c_6.setText(c6);
     pos++;
     numberOfCharactersToChange = length - pos;
    }  
        
         if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(7);
        String c7 = String.valueOf(c);
     c_7.setText(c7);
     pos++;
     numberOfCharactersToChange = length - pos;
    }   
          if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(8);
        String c8 = String.valueOf(c);
     c_8.setText(c8);
     pos++;
     numberOfCharactersToChange = length - pos;
    }
        if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(9);
        String c9 = String.valueOf(c);
     c_9.setText(c9);
     pos++;
     numberOfCharactersToChange = length - pos;
    }      
         if(numberOfCharactersToChange != 0)
    {
        char c = buff.charAt(10);
        String c10 = String.valueOf(c);
     c_10.setText(c10);
     pos++;
     numberOfCharactersToChange = length - pos;
    }     
          
   //Check to see of buffer is still empty   
   String tick ="_";
   if(buff.indexOf(tick) == -1)
        {
          JOptionPane.showMessageDialog(null, "Game won");
          //Make sound
          
        }      
          
        
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GameJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_0;
    private javax.swing.JTextField c_1;
    private javax.swing.JTextField c_10;
    private javax.swing.JTextField c_2;
    private javax.swing.JTextField c_3;
    private javax.swing.JTextField c_4;
    private javax.swing.JTextField c_5;
    private javax.swing.JTextField c_6;
    private javax.swing.JTextField c_7;
    private javax.swing.JTextField c_8;
    private javax.swing.JTextField c_9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Tries;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_previous;
    private javax.swing.JTextField txt_character;
    // End of variables declaration//GEN-END:variables
}
